cloud:
  aws:
    credentials:
      access-key: #access-key
      secret-key: #secret-key

    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: #nameOfTheBucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090